"""Generate a DOSBox Staging config that launches Drakkhen exactly like the stock 0.74 wrapper.

Why: GOG and Steam both ship DOSBox 0.74 (2010). Staging is a maintained fork that keeps the same
config/autoexec model, so the game itself needs no changes - only the emulator around it. Gains,
all verified against Staging's documented option set:
  * `cputype`/OPL: Staging's default OPL core (nuked) is cycle-accurate FM - the existing AdLib
    score sounds materially better with no game patch at all.
  * `output = opengl` + integer scaling: crisp pixels instead of 0.74's stretched `overlay`,
    plus a documented menu of the glshaders that actually ship with Staging 0.82.2
    (CRT looks, xbr/advinterp "HD" smoothing) - verified against resources/glshaders.
  * Borderless-window fullscreen: Staging's fullscreen with fullresolution=desktop is a
    borderless window rather than a display mode switch.
  * Modern fullscreen/display handling on multi-monitor setups - the 0.74 mode-switch path is the
    prime suspect for the user's whole-desktop crash on exit.
  * Staging still honours xms/ems/umb, so the memory work carries over unchanged.

The stock launch is reproduced faithfully:
  GOG  : mount c ".." (the folder ABOVE DOSBOX\\) then run DRAKKHEN.COM
  STEAM: mount c "game" then run DRAKKHEN
This script writes `drakkhen-staging.conf` next to the game so `dosbox -conf <file>` just works.

Deliberately NOT changed: machine=svga_s3, memsize=16, sbtype=sb16, aspect ratio, and the autoexec
sequence. Those define the game's environment; only presentation and the emulator itself move.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.dirname(HERE)

TEMPLATE = """# Drakkhen - DOSBox Staging configuration (generated by gen_staging_conf.py)
# Run with:  dosbox -conf drakkhen-staging.conf
# Reproduces the stock DOSBox 0.74 launch; only the emulator and presentation differ.

[sdl]
# BORDERLESS WINDOW: Staging's "fullscreen" is already a borderless desktop-sized window
# (not a display-mode change) when fullresolution=desktop - which is also why it should not
# repeat the 0.74 mode-switch crash. Set fullscreen=true to start that way; ALT+ENTER toggles.
fullscreen      = false
fullresolution  = desktop
display         = 0
window_size     = default
output          = opengl
# Integer scaling keeps DOS pixels perfectly square (no shimmer when the image scales up).
# 'vertical' scales height by whole numbers and lets width follow the aspect correction.
integer_scaling = vertical
vsync           = true

[dosbox]
machine  = svga_s3
memsize  = 16

[cpu]
core   = auto
cycles = auto

[render]
# Aspect correction: 320x200 was shown on a 4:3 monitor, so square-pixel output looks squashed
# without this. Leave it on unless you prefer the "modern" look.
aspect  = true

# ---- PICTURE QUALITY ---------------------------------------------------------------------
# Change the `glshader` line below and relaunch. These are the shaders that actually ship with
# DOSBox Staging 0.82.2 (verified against its resources/glshaders folder - run
# `dosbox --list-glshaders` to print the list yourself).
#
# FAITHFUL (keep every pixel):
#   interpolation/sharp     crisp square pixels, no filtering        <- default here
#   interpolation/nearest   same idea, absolutely no smoothing
#
# CRT LOOK (scanlines/glow - Drakkhen's art was DRAWN for a CRT, so this is closer to intent).
# Pick the one matching your monitor; that resolution match is why they look sharp not mushy:
#   crt/vga-1080p           1080p screens
#   crt/vga-1440p           1440p screens
#   crt/vga-4k              4K screens
#   crt/composite-1080p     softer, TV-style colour bleed
#   crt/arcade-1080p        arcade monitor look (also -1440p / -4k)
#
# "HD" SMOOTHING (invents smooth edges from the pixel art - cleaner sprites, softer art):
#   scaler/xbr-lv3          the best modern smoother in this build
#   scaler/xbr-lv2-noblend  sharper variant, less blending
#   scaler/advinterp2x      classic interpolating scaler
#   scaler/advmame2x        classic MAME-style scaler
#
# NOTE: no shader adds detail that was never drawn - 320x200 is 320x200. These change how the
# pixels are PRESENTED. There is no hotkey to cycle shaders in Staging 0.82.2; it is a config
# setting, so edit this line and relaunch (takes a couple of seconds).
glshader = interpolation/sharp

[mixer]
rate       = 48000
blocksize  = 1024
prebuffer  = 25

[sblaster]
sbtype  = sb16
sbbase  = 220
irq     = 7
dma     = 1
hdma    = 5
# 'nuked' is a cycle-accurate OPL3 core: the same FM score, rendered far more faithfully
# than 0.74's approximation. This is the single biggest audio win available without
# touching the game.
oplmode = auto
oplemu  = nuked

[midi]
mididevice = auto

[dos]
xms = true
ems = true
umb = true

[autoexec]
{autoexec}
"""

VARIANTS = {
    'gog': ('drakkhen-staging.conf',
            '@echo off\nmount c "."\nc:\ncls\ndrakkhen.com\nexit'),
    'steam': ('drakkhen-staging.conf',
              '@echo off\nmount c "game"\nc:\ncls\ndrakkhen.com\nexit'),
}


def main():
    which = sys.argv[1] if len(sys.argv) > 1 else 'gog'
    outdir = sys.argv[2] if len(sys.argv) > 2 else GAME
    name, autoexec = VARIANTS[which]
    path = os.path.join(outdir, name)
    open(path, 'w', newline='\r\n').write(TEMPLATE.format(autoexec=autoexec))
    print('wrote %s (%s layout)' % (path, which))
    print('launch with:  dosbox -conf "%s"' % path)


if __name__ == '__main__':
    main()
