# Drakkhen QOL patch - US GOG version. Generated by make_patcher.py; do not edit by hand.
# Usage:  powershell -ExecutionPolicy Bypass -File install.ps1 [-GamePath <dir>] [-Restore]
param(
    [string]$GamePath = $PSScriptRoot,
    [switch]$Restore
)
$ErrorActionPreference = 'Stop'

function Get-Sha([byte[]]$b) {
    $h = [System.Security.Cryptography.SHA256]::Create().ComputeHash($b)
    -join ($h | ForEach-Object { $_.ToString('x2') })
}
function Fail($msg) { Write-Host "ERROR: $msg" -ForegroundColor Red; exit 1 }

# ---- locate the game -------------------------------------------------------
if (-not (Test-Path (Join-Path $GamePath 'DRAKM.CC1'))) {
    Fail "DRAKM.CC1 not found in '$GamePath'. Put install.ps1 in the Drakkhen game folder, or pass -GamePath."
}
$drakm = Join-Path $GamePath 'DRAKM.CC1'
$resi  = Join-Path $GamePath 'RESI_VGA.6C0'
$map   = Join-Path $GamePath 'MAP.DRK'
$bak   = Join-Path $GamePath '_backup\original'
if (-not (Test-Path $resi)) { Fail "RESI_VGA.6C0 not found in '$GamePath'." }

# ---- restore mode ----------------------------------------------------------
if ($Restore) {
    foreach ($f in 'DRAKM.CC1', 'RESI_VGA.6C0') {
        $src = Join-Path $bak $f
        if (-not (Test-Path $src)) { Fail "no backup at $src - nothing to restore." }
        Copy-Item $src (Join-Path $GamePath $f) -Force
        Write-Host "restored $f"
    }
    if (Test-Path $map) { Remove-Item $map; Write-Host 'removed MAP.DRK (added by the patch)' }
    Write-Host 'Game restored to stock. Save files were not touched.' -ForegroundColor Green
    exit 0
}

# ---- BPE codec (C# port of the reference drakpack.py) ----------------------
Add-Type -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.IO;
public static class DrakPack {
    // Decode one BPE chunk starting at pos (after any headers). Mirrors bpe_decode().
    public static byte[] Decode(byte[] src, int pos) {
        var outb = new List<byte>();
        while (true) {
            int n = src[pos], more = src[pos+1];
            int len = src[pos+2] | (src[pos+3] << 8);
            pos += 4;
            if (n == 0) {
                for (int i = 0; i < len; i++) outb.Add(src[pos+i]);
                pos += len;
            } else {
                int cbase = pos, lbase = pos + n, rbase = pos + 2*n;
                pos += 3*n;
                var t = new int[256];
                var chain = new int[n+1];
                for (int i = 1; i <= n; i++) { chain[i] = t[src[cbase+i-1]]; t[src[cbase+i-1]] = i; }
                for (int k = 0; k < len; k++) Expand(src, cbase, lbase, rbase, t, chain, src[pos+k], -1, outb);
                pos += len;
            }
            if (more == 0) return outb.ToArray();
        }
    }
    static void Expand(byte[] src, int cbase, int lbase, int rbase, int[] t, int[] chain,
                       byte b, int limit, List<byte> outb) {
        int idx = t[b];
        if (idx == 0) { outb.Add(b); return; }
        if (limit >= 0 && limit <= idx) {
            int j = idx;
            while (true) {
                j = chain[j];
                if (j == 0) { outb.Add(b); return; }
                if (j < limit) { idx = j; break; }
            }
        }
        Expand(src, cbase, lbase, rbase, t, chain, src[lbase+idx-1], idx, outb);
        Expand(src, cbase, lbase, rbase, t, chain, src[rbase+idx-1], idx, outb);
    }
    // Store raw npairs=0 blocks. Mirrors bpe_encode_raw().
    public static byte[] EncodeRaw(byte[] raw) {
        var ms = new MemoryStream();
        int nblocks = Math.Max(1, (raw.Length + 0xFFBF) / 0xFFC0);
        for (int i = 0; i < nblocks; i++) {
            int off = i * 0xFFC0;
            int len = Math.Min(0xFFC0, raw.Length - off);
            ms.WriteByte(0);
            ms.WriteByte((byte)(i < nblocks-1 ? 1 : 0));
            ms.WriteByte((byte)(len & 0xFF));
            ms.WriteByte((byte)(len >> 8));
            ms.Write(raw, off, len);
        }
        return ms.ToArray();
    }
    static void WriteBE(MemoryStream ms, uint v) {
        ms.WriteByte((byte)(v >> 24)); ms.WriteByte((byte)(v >> 16));
        ms.WriteByte((byte)(v >> 8));  ms.WriteByte((byte)v);
    }
    // Mirrors pack_container(): u16be n, n*u32be offsets, [u32be packed][u32be unpacked][body] each.
    public static byte[] PackContainer(byte[][] chunks) {
        var bodies = new byte[chunks.Length][];
        for (int i = 0; i < chunks.Length; i++) bodies[i] = EncodeRaw(chunks[i]);
        var ms = new MemoryStream();
        ms.WriteByte((byte)(chunks.Length >> 8)); ms.WriteByte((byte)chunks.Length);
        uint off = 0;
        for (int i = 0; i < chunks.Length; i++) { WriteBE(ms, off); off += (uint)(bodies[i].Length + 8); }
        for (int i = 0; i < chunks.Length; i++) {
            WriteBE(ms, (uint)bodies[i].Length); WriteBE(ms, (uint)chunks[i].Length);
            ms.Write(bodies[i], 0, bodies[i].Length);
        }
        return ms.ToArray();
    }
    // Split a container into decoded chunks.
    public static byte[][] UnpackContainer(byte[] data) {
        int n = (data[0] << 8) | data[1];
        var res = new byte[n][];
        int tbl = 2, basep = 2 + 4*n;
        for (int i = 0; i < n; i++) {
            int o = (data[tbl+4*i] << 24) | (data[tbl+4*i+1] << 16) | (data[tbl+4*i+2] << 8) | data[tbl+4*i+3];
            res[i] = Decode(data, basep + o + 8);
        }
        return res;
    }
}
'@

# ---- embedded patch data ---------------------------------------------------
$stockDrakmSha = '@@STOCK_DRAKM_SHA@@'
$stockResiSha  = '@@STOCK_RESI_SHA@@'
$modDrakmSha   = '@@MOD_DRAKM_SHA@@'
$modResiSha    = '@@MOD_RESI_SHA@@'
$mapSha        = '@@MAP_SHA@@'
$diffDrakm = @'
@@DIFF_LINES@@
'@
$diffResi = @'
@@RDIFF_LINES@@
'@
$mapB64 = '@@MAP_B64@@'

function Apply-Diff([byte[]]$img, [string]$diff) {
    foreach ($line in ($diff -split "`n")) {
        $line = $line.Trim(); if (-not $line) { continue }
        $p = $line.Split(':'); $off = [int]$p[0]; $hex = $p[1]
        for ($i = 0; $i -lt $hex.Length; $i += 2) {
            $img[$off + ($i/2)] = [Convert]::ToByte($hex.Substring($i, 2), 16)
        }
    }
}

# ---- verify the stock files ------------------------------------------------
$drakmBytes = [IO.File]::ReadAllBytes($drakm)
$resiBytes  = [IO.File]::ReadAllBytes($resi)
$dSha = Get-Sha $drakmBytes; $rSha = Get-Sha $resiBytes
if ($dSha -eq $modDrakmSha -and $rSha -eq $modResiSha) {
    Write-Host 'Already patched with this version - nothing to do.' -ForegroundColor Green; exit 0
}
# allow re-patching a modified install from its own backup
if ($dSha -ne $stockDrakmSha -and (Test-Path (Join-Path $bak 'DRAKM.CC1'))) {
    $drakmBytes = [IO.File]::ReadAllBytes((Join-Path $bak 'DRAKM.CC1')); $dSha = Get-Sha $drakmBytes
    Write-Host 'DRAKM.CC1 is modified; using the backup copy as the stock source.'
}
if ($rSha -ne $stockResiSha -and (Test-Path (Join-Path $bak 'RESI_VGA.6C0'))) {
    $resiBytes = [IO.File]::ReadAllBytes((Join-Path $bak 'RESI_VGA.6C0')); $rSha = Get-Sha $resiBytes
    Write-Host 'RESI_VGA.6C0 is modified; using the backup copy as the stock source.'
}
if ($dSha -ne $stockDrakmSha) { Fail "DRAKM.CC1 is not the stock US GOG version (SHA256 $dSha). This patch supports only that version; nothing was changed." }
if ($rSha -ne $stockResiSha)  { Fail "RESI_VGA.6C0 is not the stock US GOG version (SHA256 $rSha). Nothing was changed." }

# ---- back up ---------------------------------------------------------------
New-Item -ItemType Directory -Force $bak | Out-Null
foreach ($f in @{ 'DRAKM.CC1' = $drakmBytes; 'RESI_VGA.6C0' = $resiBytes }.GetEnumerator()) {
    $dst = Join-Path $bak $f.Key
    if (-not (Test-Path $dst)) { [IO.File]::WriteAllBytes($dst, $f.Value); Write-Host "backed up $($f.Key)" }
}

# ---- rebuild DRAKM.CC1 -----------------------------------------------------
Write-Host 'decoding DRAKM.CC1 ...'
$chunks = [DrakPack]::UnpackContainer($drakmBytes)
Apply-Diff $chunks[1] $diffDrakm
$newDrakm = [DrakPack]::PackContainer($chunks)
if ((Get-Sha $newDrakm) -ne $modDrakmSha) { Fail 'rebuilt DRAKM.CC1 failed verification - nothing was changed.' }

# ---- rebuild RESI_VGA.6C0 --------------------------------------------------
Write-Host 'decoding RESI_VGA.6C0 ...'
$rdec = [DrakPack]::Decode($resiBytes, 8)
Apply-Diff $rdec $diffResi
$rbody = [DrakPack]::EncodeRaw($rdec)
$ms = New-Object IO.MemoryStream
foreach ($v in @($rbody.Length, $rdec.Length)) {
    $ms.WriteByte([byte](($v -shr 24) -band 0xFF)); $ms.WriteByte([byte](($v -shr 16) -band 0xFF))
    $ms.WriteByte([byte](($v -shr 8) -band 0xFF));  $ms.WriteByte([byte]($v -band 0xFF))
}
$ms.Write($rbody, 0, $rbody.Length)
$newResi = $ms.ToArray()
if ((Get-Sha $newResi) -ne $modResiSha) { Fail 'rebuilt RESI_VGA.6C0 failed verification - nothing was changed.' }

# ---- MAP.DRK ---------------------------------------------------------------
$mapBytes = [Convert]::FromBase64String($mapB64)
if ((Get-Sha $mapBytes) -ne $mapSha) { Fail 'embedded MAP.DRK failed verification.' }

# ---- commit (only after every verification passed) -------------------------
[IO.File]::WriteAllBytes($drakm, $newDrakm)
[IO.File]::WriteAllBytes($resi, $newResi)
[IO.File]::WriteAllBytes($map, $mapBytes)
Write-Host ''
Write-Host 'Patched successfully:' -ForegroundColor Green
Write-Host '  DRAKM.CC1     - compass, M-key world map, MP regen, shared XP, item names'
Write-Host '  RESI_VGA.6C0  - readable spell font'
Write-Host '  MAP.DRK       - world map image (new file)'
Write-Host 'Originals are in _backup\original. Uninstall:  install.ps1 -Restore'
