#!/usr/bin/env python3
"""Drakkhen QOL patch - US GOG version. Python installer (stdlib only, no dependencies).

Same behavior as install.ps1: verifies your files are the stock US GOG release by SHA256,
backs them up, rebuilds the patched files FROM YOUR OWN GAME DATA, verifies the result
byte-for-byte against the reference build, and only then writes. Save files are never touched.

    python install.py            (run from the Drakkhen game folder, or pass the path)
    python install.py --restore  (uninstall: put the backed-up originals back)

Generated by make_patcher.py; do not edit by hand.
"""
import argparse, base64, hashlib, os, struct, sys

STOCK_DRAKM_SHA = '@@STOCK_DRAKM_SHA@@'
STOCK_RESI_SHA  = '@@STOCK_RESI_SHA@@'
MOD_DRAKM_SHA   = '@@MOD_DRAKM_SHA@@'
MOD_RESI_SHA    = '@@MOD_RESI_SHA@@'
MAP_SHA         = '@@MAP_SHA@@'

DIFF_DRAKM = '''@@DIFF_LINES@@'''
DIFF_RESI  = '''@@RDIFF_LINES@@'''
MAP_B64    = '@@MAP_B64@@'


# ---- BPE codec (mirrors the reference drakpack.py) --------------------------
def bpe_decode(src, pos):
    out = bytearray()
    while True:
        n, more = src[pos], src[pos + 1]
        ln = src[pos + 2] | (src[pos + 3] << 8)
        pos += 4
        if n == 0:
            out += src[pos:pos + ln]; pos += ln
        else:
            code = src[pos:pos + n]; left = src[pos + n:pos + 2 * n]; right = src[pos + 2 * n:pos + 3 * n]
            pos += 3 * n
            t = [0] * 256; chain = [0] * (n + 1)
            for i in range(1, n + 1):
                chain[i] = t[code[i - 1]]; t[code[i - 1]] = i
            for b in src[pos:pos + ln]:
                stack = [(b, -1)]
                while stack:
                    b2, limit = stack.pop()
                    idx = t[b2]
                    if idx and 0 <= limit <= idx:
                        j = idx
                        while True:
                            j = chain[j]
                            if j == 0:
                                idx = 0; break
                            if j < limit:
                                idx = j; break
                    if idx == 0:
                        out.append(b2)
                    else:
                        stack.append((right[idx - 1], idx))
                        stack.append((left[idx - 1], idx))
            pos += ln
        if not more:
            return bytes(out), pos


def encode_raw(raw):
    out = bytearray()
    blocks = [raw[i:i + 0xFFC0] for i in range(0, len(raw), 0xFFC0)] or [b'']
    for i, b in enumerate(blocks):
        out += struct.pack('<BBH', 0, 1 if i < len(blocks) - 1 else 0, len(b)) + b
    return bytes(out)


def pack_container(chunks):
    bodies = [struct.pack('>II', len(encode_raw(c)), len(c)) + encode_raw(c) for c in chunks]
    offs, o = [], 0
    for b in bodies:
        offs.append(o); o += len(b)
    return (struct.pack('>H', len(chunks)) + b''.join(struct.pack('>I', x) for x in offs)
            + b''.join(bodies))


def unpack_container(data):
    n = struct.unpack_from('>H', data)[0]
    base = 2 + 4 * n
    res = []
    for i in range(n):
        o = struct.unpack_from('>I', data, 2 + 4 * i)[0]
        res.append(bpe_decode(data, base + o + 8)[0])
    return res


# ---- helpers ----------------------------------------------------------------
def sha(b): return hashlib.sha256(b).hexdigest()

def apply_diff(img, diff):
    img = bytearray(img)
    for line in diff.splitlines():
        line = line.strip()
        if not line:
            continue
        off, hexs = line.split(':')
        img[int(off):int(off) + len(hexs) // 2] = bytes.fromhex(hexs)
    return bytes(img)

def fail(msg):
    print('ERROR: ' + msg); sys.exit(1)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('gamepath', nargs='?', default=os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument('--restore', action='store_true', help='undo the patch from the backup')
    a = ap.parse_args()
    g = a.gamepath
    drakm, resi = os.path.join(g, 'DRAKM.CC1'), os.path.join(g, 'RESI_VGA.6C0')
    mapf = os.path.join(g, 'MAP.DRK')
    bak = os.path.join(g, '_backup', 'original')
    if not os.path.exists(drakm) or not os.path.exists(resi):
        fail("game files not found in '%s' - run from the Drakkhen folder or pass its path." % g)

    if a.restore:
        for f in ('DRAKM.CC1', 'RESI_VGA.6C0'):
            src = os.path.join(bak, f)
            if not os.path.exists(src):
                fail('no backup at %s - nothing to restore.' % src)
            open(os.path.join(g, f), 'wb').write(open(src, 'rb').read())
            print('restored ' + f)
        if os.path.exists(mapf):
            os.remove(mapf); print('removed MAP.DRK (added by the patch)')
        print('Game restored to stock. Save files were not touched.')
        return

    db, rb = open(drakm, 'rb').read(), open(resi, 'rb').read()
    if sha(db) == MOD_DRAKM_SHA and sha(rb) == MOD_RESI_SHA:
        print('Already patched with this version - nothing to do.'); return
    if sha(db) != STOCK_DRAKM_SHA and os.path.exists(os.path.join(bak, 'DRAKM.CC1')):
        db = open(os.path.join(bak, 'DRAKM.CC1'), 'rb').read()
        print('DRAKM.CC1 is modified; using the backup copy as the stock source.')
    if sha(rb) != STOCK_RESI_SHA and os.path.exists(os.path.join(bak, 'RESI_VGA.6C0')):
        rb = open(os.path.join(bak, 'RESI_VGA.6C0'), 'rb').read()
        print('RESI_VGA.6C0 is modified; using the backup copy as the stock source.')
    if sha(db) != STOCK_DRAKM_SHA:
        fail('DRAKM.CC1 is not the stock US GOG version (SHA256 %s). Nothing was changed.' % sha(db))
    if sha(rb) != STOCK_RESI_SHA:
        fail('RESI_VGA.6C0 is not the stock US GOG version. Nothing was changed.')

    os.makedirs(bak, exist_ok=True)
    for name, data in (('DRAKM.CC1', db), ('RESI_VGA.6C0', rb)):
        p = os.path.join(bak, name)
        if not os.path.exists(p):
            open(p, 'wb').write(data); print('backed up ' + name)

    print('decoding DRAKM.CC1 ...')
    chunks = unpack_container(db)
    chunks[1] = apply_diff(chunks[1], DIFF_DRAKM)
    new_drakm = pack_container(chunks)
    if sha(new_drakm) != MOD_DRAKM_SHA:
        fail('rebuilt DRAKM.CC1 failed verification - nothing was changed.')

    print('decoding RESI_VGA.6C0 ...')
    rdec = apply_diff(bpe_decode(rb, 8)[0], DIFF_RESI)
    body = encode_raw(rdec)
    new_resi = struct.pack('>II', len(body), len(rdec)) + body
    if sha(new_resi) != MOD_RESI_SHA:
        fail('rebuilt RESI_VGA.6C0 failed verification - nothing was changed.')

    map_bytes = base64.b64decode(MAP_B64)
    if sha(map_bytes) != MAP_SHA:
        fail('embedded MAP.DRK failed verification.')

    open(drakm, 'wb').write(new_drakm)
    open(resi, 'wb').write(new_resi)
    open(mapf, 'wb').write(map_bytes)
    print('')
    print('Patched successfully:')
    print('  DRAKM.CC1     - compass, M-key world map, shared XP, item names, bow buff')
    print('  RESI_VGA.6C0  - readable spell font')
    print('  MAP.DRK       - world map image (new file)')
    print('Originals are in _backup/original. Uninstall:  python install.py --restore')


if __name__ == '__main__':
    main()
