# Drakkhen QOL patch - US GOG version. Generated by make_patcher.py; do not edit by hand.
# Usage:  powershell -ExecutionPolicy Bypass -File install.ps1 [-GamePath <dir>] [-Restore]
param(
    [string]$GamePath = $PSScriptRoot,
    [switch]$Restore,
    [switch]$All,
    [string]$Mods
)
$ErrorActionPreference = 'Stop'

function Get-Sha([byte[]]$b) {
    $h = [System.Security.Cryptography.SHA256]::Create().ComputeHash($b)
    -join ($h | ForEach-Object { $_.ToString('x2') })
}
function Fail($msg) { Write-Host "ERROR: $msg" -ForegroundColor Red; exit 1 }

# ---- locate the game -------------------------------------------------------
if (-not (Test-Path (Join-Path $GamePath 'DRAKM.CC1')) -and
    (Test-Path (Join-Path $GamePath 'game\DRAKM.CC1'))) {
    $GamePath = Join-Path $GamePath 'game'      # Steam layout: files live in a game/ subfolder
    Write-Host "using Steam layout: game files in '$GamePath'"
}
if (-not (Test-Path (Join-Path $GamePath 'DRAKM.CC1'))) {
    Fail "DRAKM.CC1 not found in '$GamePath'. Put install.ps1 in the Drakkhen game folder, or pass -GamePath."
}
$drakm = Join-Path $GamePath 'DRAKM.CC1'
$resi  = Join-Path $GamePath 'RESI_VGA.6C0'
$map   = Join-Path $GamePath 'MAP.DRK'
$bak   = Join-Path $GamePath '_backup\original'
if (-not (Test-Path $resi)) { Fail "RESI_VGA.6C0 not found in '$GamePath'." }

# ---- restore mode ----------------------------------------------------------
if ($Restore) {
    foreach ($f in 'DRAKM.CC1', 'RESI_VGA.6C0') {
        $src = Join-Path $bak $f
        if (-not (Test-Path $src)) { Fail "no backup at $src - nothing to restore." }
        Copy-Item $src (Join-Path $GamePath $f) -Force
        Write-Host "restored $f"
    }
    if (Test-Path $map) { Remove-Item $map; Write-Host 'removed MAP.DRK (added by the patch)' }
    $quest = Join-Path $GamePath 'QUEST.DRK'
    if (Test-Path $quest) { Remove-Item $quest; Write-Host 'removed QUEST.DRK (added by the patch)' }
    $cfg = Join-Path $GamePath 'CONFIG.TAT'
    if (Test-Path $cfg) {
        $cb = [IO.File]::ReadAllBytes($cfg)
        if ($cb.Length -gt 0x0B) { $cb[0x0A] = 0xFF; $cb[0x0B] = 0xFF; [IO.File]::WriteAllBytes($cfg, $cb)
            Write-Host 'restored CONFIG.TAT video-card prompt' }
    }
    Write-Host 'Game restored to stock. Save files were not touched.' -ForegroundColor Green
    exit 0
}

# ---- BPE codec (C# port of the reference drakpack.py) ----------------------
Add-Type -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.IO;
public static class DrakPack {
    // Decode one BPE chunk starting at pos (after any headers). Mirrors bpe_decode().
    public static byte[] Decode(byte[] src, int pos) {
        var outb = new List<byte>();
        while (true) {
            int n = src[pos], more = src[pos+1];
            int len = src[pos+2] | (src[pos+3] << 8);
            pos += 4;
            if (n == 0) {
                for (int i = 0; i < len; i++) outb.Add(src[pos+i]);
                pos += len;
            } else {
                int cbase = pos, lbase = pos + n, rbase = pos + 2*n;
                pos += 3*n;
                var t = new int[256];
                var chain = new int[n+1];
                for (int i = 1; i <= n; i++) { chain[i] = t[src[cbase+i-1]]; t[src[cbase+i-1]] = i; }
                for (int k = 0; k < len; k++) Expand(src, cbase, lbase, rbase, t, chain, src[pos+k], -1, outb);
                pos += len;
            }
            if (more == 0) return outb.ToArray();
        }
    }
    static void Expand(byte[] src, int cbase, int lbase, int rbase, int[] t, int[] chain,
                       byte b, int limit, List<byte> outb) {
        int idx = t[b];
        if (idx == 0) { outb.Add(b); return; }
        if (limit >= 0 && limit <= idx) {
            int j = idx;
            while (true) {
                j = chain[j];
                if (j == 0) { outb.Add(b); return; }
                if (j < limit) { idx = j; break; }
            }
        }
        Expand(src, cbase, lbase, rbase, t, chain, src[lbase+idx-1], idx, outb);
        Expand(src, cbase, lbase, rbase, t, chain, src[rbase+idx-1], idx, outb);
    }
    // Store raw npairs=0 blocks. Mirrors bpe_encode_raw().
    public static byte[] EncodeRaw(byte[] raw) {
        var ms = new MemoryStream();
        int nblocks = Math.Max(1, (raw.Length + 0xFFBF) / 0xFFC0);
        for (int i = 0; i < nblocks; i++) {
            int off = i * 0xFFC0;
            int len = Math.Min(0xFFC0, raw.Length - off);
            ms.WriteByte(0);
            ms.WriteByte((byte)(i < nblocks-1 ? 1 : 0));
            ms.WriteByte((byte)(len & 0xFF));
            ms.WriteByte((byte)(len >> 8));
            ms.Write(raw, off, len);
        }
        return ms.ToArray();
    }
    static void WriteBE(MemoryStream ms, uint v) {
        ms.WriteByte((byte)(v >> 24)); ms.WriteByte((byte)(v >> 16));
        ms.WriteByte((byte)(v >> 8));  ms.WriteByte((byte)v);
    }
    // Mirrors pack_container(): u16be n, n*u32be offsets, [u32be packed][u32be unpacked][body] each.
    public static byte[] PackContainer(byte[][] chunks) {
        var bodies = new byte[chunks.Length][];
        for (int i = 0; i < chunks.Length; i++) bodies[i] = EncodeRaw(chunks[i]);
        var ms = new MemoryStream();
        ms.WriteByte((byte)(chunks.Length >> 8)); ms.WriteByte((byte)chunks.Length);
        uint off = 0;
        for (int i = 0; i < chunks.Length; i++) { WriteBE(ms, off); off += (uint)(bodies[i].Length + 8); }
        for (int i = 0; i < chunks.Length; i++) {
            WriteBE(ms, (uint)bodies[i].Length); WriteBE(ms, (uint)chunks[i].Length);
            ms.Write(bodies[i], 0, bodies[i].Length);
        }
        return ms.ToArray();
    }
    // Split a container into decoded chunks.
    public static byte[][] UnpackContainer(byte[] data) {
        int n = (data[0] << 8) | data[1];
        var res = new byte[n][];
        int tbl = 2, basep = 2 + 4*n;
        for (int i = 0; i < n; i++) {
            int o = (data[tbl+4*i] << 24) | (data[tbl+4*i+1] << 16) | (data[tbl+4*i+2] << 8) | data[tbl+4*i+3];
            res[i] = Decode(data, basep + o + 8);
        }
        return res;
    }
}
'@

# ---- embedded patch data ---------------------------------------------------
$stockDrakmSha = '@@STOCK_DRAKM_SHA@@'
$steamDrakmSha = '@@STEAM_DRAKM_SHA@@'   # GOG stock + Steam's own 1-byte protection skip
$stockResiSha  = '@@STOCK_RESI_SHA@@'
$modDrakmSha   = '@@MOD_DRAKM_SHA@@'
$modResiSha    = '@@MOD_RESI_SHA@@'
$mapSha        = '@@MAP_SHA@@'
$diffDrakm = @'
@@DIFF_LINES@@
'@
$diffResi = @'
@@RDIFF_LINES@@
'@
$mapB64 = '@@MAP_B64@@'
$questSha = '@@QUEST_SHA@@'
$questB64 = '@@QUEST_B64@@'
$frags   = '@@FRAGS_JSON@@' | ConvertFrom-Json
$moddefs = '@@MODDEFS_JSON@@' | ConvertFrom-Json

function Ask-Selection {
    Add-Type -AssemblyName System.Windows.Forms
    Add-Type -AssemblyName System.Drawing
    $form = New-Object Windows.Forms.Form
    $form.Text = 'Drakkhen QOL - choose your mods'
    $form.Size = New-Object Drawing.Size(430, (120 + 26 * ($moddefs.Count + 1)))
    $form.FormBorderStyle = 'FixedDialog'; $form.MaximizeBox = $false
    $chkAll = New-Object Windows.Forms.CheckBox
    $chkAll.Text = 'Check all'; $chkAll.Checked = $true
    $chkAll.Location = New-Object Drawing.Point(15, 12)
    $chkAll.Width = 380; $chkAll.Font = New-Object Drawing.Font($chkAll.Font, [Drawing.FontStyle]::Bold)
    $form.Controls.Add($chkAll)
    $boxes = @{}
    $y = 42
    foreach ($m in $moddefs) {
        $cb = New-Object Windows.Forms.CheckBox
        $cb.Text = $m[1]; $cb.Checked = $true
        $cb.Location = New-Object Drawing.Point(30, $y); $cb.Width = 370
        $form.Controls.Add($cb); $boxes[$m[0]] = $cb; $y += 26
    }
    $chkAll.Add_CheckedChanged({ foreach ($cb in $boxes.Values) { $cb.Checked = $chkAll.Checked } })
    $ok = New-Object Windows.Forms.Button
    $ok.Text = 'Install'; $ok.DialogResult = 'OK'
    $ok.Location = New-Object Drawing.Point(230, ($y + 8))
    $cancel = New-Object Windows.Forms.Button
    $cancel.Text = 'Cancel'; $cancel.DialogResult = 'Cancel'
    $cancel.Location = New-Object Drawing.Point(315, ($y + 8))
    $form.Controls.Add($ok); $form.Controls.Add($cancel)
    $form.AcceptButton = $ok; $form.CancelButton = $cancel
    if ($form.ShowDialog() -ne 'OK') { Write-Host 'cancelled - nothing was changed.'; exit 0 }
    $sel = New-Object System.Collections.Generic.HashSet[string]
    foreach ($k in $boxes.Keys) { if ($boxes[$k].Checked) { [void]$sel.Add($k) } }
    return $sel
}

# Chunk 0 of DRAKM.CC1 is the character creator (a second MZ image).  Mods that change what a
# new character starts with edit immediate operands there, so no relocation work is needed.
function Apply-CreatorFragments([byte[]]$c, $selected) {
    foreach ($name in $frags.order) {
        if (-not $selected.Contains($name)) { continue }
        $w0 = $frags.frags.$name.writes0
        if ($null -eq $w0) { continue }
        foreach ($w in $w0) {
            $off = [int]$w[0]; $hex = $w[1]
            for ($i = 0; $i -lt $hex.Length; $i += 2) {
                $c[$off + ($i / 2)] = [Convert]::ToByte($hex.Substring($i, 2), 16)
            }
        }
    }
    return ,$c
}

function Apply-Fragments([byte[]]$c, $selected) {
    $ro = [BitConverter]::ToUInt16($c, 24); $nrel = [BitConverter]::ToUInt16($c, 6)
    $hdr = [BitConverter]::ToUInt16($c, 8) * 16
    foreach ($name in $frags.order) {
        if (-not $selected.Contains($name)) { continue }
        foreach ($w in $frags.frags.$name.writes) {
            $off = [int]$w[0]; $hex = $w[1]
            for ($i = 0; $i -lt $hex.Length; $i += 2) {
                $c[$off + ($i / 2)] = [Convert]::ToByte($hex.Substring($i, 2), 16)
            }
        }
    }
    $reps = @{}; $drops = New-Object System.Collections.Generic.HashSet[int]; $adds = @()
    foreach ($name in $frags.order) {
        if (-not $selected.Contains($name)) { continue }
        $f = $frags.frags.$name
        foreach ($r in $f.rrep)  { $reps[[int]$r[0]] = @([int]$r[1], [int]$r[2]) }
        foreach ($x in $f.rdrop) { [void]$drops.Add([int]$x) }
        foreach ($a in $f.radd)  { $adds += , @([int]$a[0], [int]$a[1]) }
    }
    $entries = @()
    for ($i = 0; $i -lt $nrel; $i++) {
        $off = [BitConverter]::ToUInt16($c, $ro + 4 * $i)
        $seg = [BitConverter]::ToUInt16($c, $ro + 4 * $i + 2)
        $lin = $seg * 16 + $off
        if ($drops.Contains($lin)) { continue }
        if ($reps.ContainsKey($lin)) { $off = $reps[$lin][0]; $seg = $reps[$lin][1] }
        $entries += , @($off, $seg)
    }
    $entries += $adds
    if ($ro + $entries.Count * 4 -gt $hdr) { Fail 'relocation table overflow - report this selection as a bug' }
    for ($k = 0; $k -lt $entries.Count; $k++) {
        [BitConverter]::GetBytes([uint16]$entries[$k][0]).CopyTo($c, $ro + 4 * $k)
        [BitConverter]::GetBytes([uint16]$entries[$k][1]).CopyTo($c, $ro + 4 * $k + 2)
    }
    [BitConverter]::GetBytes([uint16]$entries.Count).CopyTo($c, 6)
    return $c
}

function Apply-Diff([byte[]]$img, [string]$diff) {
    foreach ($line in ($diff -split "`n")) {
        $line = $line.Trim(); if (-not $line) { continue }
        $p = $line.Split(':'); $off = [int]$p[0]; $hex = $p[1]
        for ($i = 0; $i -lt $hex.Length; $i += 2) {
            $img[$off + ($i/2)] = [Convert]::ToByte($hex.Substring($i, 2), 16)
        }
    }
}

# ---- mod selection ---------------------------------------------------------
$allkeys = @($moddefs | ForEach-Object { $_[0] })
if ($Mods) {
    $sel = New-Object System.Collections.Generic.HashSet[string]
    foreach ($k in $Mods.Split(',')) { [void]$sel.Add($k.Trim()) }
    foreach ($k in $sel) { if ($allkeys -notcontains $k) { Fail "unknown mod key '$k'" } }
} elseif ($All) {
    $sel = New-Object System.Collections.Generic.HashSet[string]
    foreach ($k in $allkeys) { [void]$sel.Add($k) }
} else {
    $sel = Ask-Selection
}
$changed = $true
while ($changed) {
    $changed = $false
    foreach ($m in $moddefs) {
        if ($sel.Contains($m[0])) {
            foreach ($dep in $m[2]) {
                if (-not $sel.Contains($dep)) {
                    [void]$sel.Add($dep); $changed = $true
                    Write-Host "note: $($m[0]) requires $dep - enabled automatically"
                }
            }
        }
    }
}
if ($sel.Count -eq 0) { Write-Host 'nothing selected - nothing to do.'; exit 0 }
$fullSel = ($sel.Count -eq $allkeys.Count)
Write-Host ('installing: ' + (($allkeys | Where-Object { $sel.Contains($_) }) -join ', '))

# ---- verify the stock files ------------------------------------------------
$drakmBytes = [IO.File]::ReadAllBytes($drakm)
$resiBytes  = [IO.File]::ReadAllBytes($resi)
$dSha = Get-Sha $drakmBytes; $rSha = Get-Sha $resiBytes
if ($dSha -eq $modDrakmSha -and $rSha -eq $modResiSha) {
    Write-Host 'Already patched with this version - nothing to do.' -ForegroundColor Green; exit 0
}
# allow re-patching a modified install from its own backup
if ($dSha -ne $stockDrakmSha -and (Test-Path (Join-Path $bak 'DRAKM.CC1'))) {
    $drakmBytes = [IO.File]::ReadAllBytes((Join-Path $bak 'DRAKM.CC1')); $dSha = Get-Sha $drakmBytes
    Write-Host 'DRAKM.CC1 is modified; using the backup copy as the stock source.'
}
if ($rSha -ne $stockResiSha -and (Test-Path (Join-Path $bak 'RESI_VGA.6C0'))) {
    $resiBytes = [IO.File]::ReadAllBytes((Join-Path $bak 'RESI_VGA.6C0')); $rSha = Get-Sha $resiBytes
    Write-Host 'RESI_VGA.6C0 is modified; using the backup copy as the stock source.'
}
$steam = ($dSha -eq $steamDrakmSha)
if ($steam) { Write-Host 'Steam release detected (DRAKM.CC1 carries the Steam 1-byte protection skip).' }
if (-not $steam -and $dSha -ne $stockDrakmSha) {
    Fail ("DRAKM.CC1 is not a known US release.`n" +
          "  yours:       $dSha ($($drakmBytes.Length) bytes)`n" +
          "  known GOG:   $stockDrakmSha`n" +
          "  known Steam: $steamDrakmSha`n" +
          "If this is an unmodified US GOG or Steam install, please report these lines at`n" +
          "https://github.com/Innsomatico/DrakkhenPC-QOL/issues - the hash is what we need.`n" +
          "Nothing was changed.")
}
if ($rSha -ne $stockResiSha) {
    Fail ("RESI_VGA.6C0 is not the stock US version.`n" +
          "  yours: $rSha ($($resiBytes.Length) bytes)`n" +
          "  known: $stockResiSha`n" +
          "Please report these lines at https://github.com/Innsomatico/DrakkhenPC-QOL/issues.`n" +
          "Nothing was changed.")
}

# ---- back up ---------------------------------------------------------------
New-Item -ItemType Directory -Force $bak | Out-Null
foreach ($f in @{ 'DRAKM.CC1' = $drakmBytes; 'RESI_VGA.6C0' = $resiBytes }.GetEnumerator()) {
    $dst = Join-Path $bak $f.Key
    if (-not (Test-Path $dst)) { [IO.File]::WriteAllBytes($dst, $f.Value); Write-Host "backed up $($f.Key)" }
}

# ---- rebuild DRAKM.CC1 -----------------------------------------------------
Write-Host 'decoding DRAKM.CC1 ...'
$chunks = [DrakPack]::UnpackContainer($drakmBytes)
if ($steam) { $chunks[1][0x11D87] = 0x75 }   # normalize Steam's protection byte back to stock
$chunks[0] = Apply-CreatorFragments $chunks[0] $sel
$chunks[1] = Apply-Fragments $chunks[1] $sel
$newDrakm = [DrakPack]::PackContainer($chunks)
if ($fullSel -and (Get-Sha $newDrakm) -ne $modDrakmSha) { Fail 'rebuilt DRAKM.CC1 failed verification - nothing was changed.' }
if (-not $fullSel) { Write-Host 'note: partial selection - engine verified structurally (full-set hash check skipped).' }

# ---- rebuild RESI_VGA.6C0 --------------------------------------------------
$newResi = $null
if ($sel.Contains('spellfont')) {
    Write-Host 'decoding RESI_VGA.6C0 ...'
    $rdec = [DrakPack]::Decode($resiBytes, 8)
    Apply-Diff $rdec $diffResi
    $rbody = [DrakPack]::EncodeRaw($rdec)
    $ms = New-Object IO.MemoryStream
    foreach ($v in @($rbody.Length, $rdec.Length)) {
        $ms.WriteByte([byte](($v -shr 24) -band 0xFF)); $ms.WriteByte([byte](($v -shr 16) -band 0xFF))
        $ms.WriteByte([byte](($v -shr 8) -band 0xFF));  $ms.WriteByte([byte]($v -band 0xFF))
    }
    $ms.Write($rbody, 0, $rbody.Length)
    $newResi = $ms.ToArray()
    if ((Get-Sha $newResi) -ne $modResiSha) { Fail 'rebuilt RESI_VGA.6C0 failed verification - nothing was changed.' }
}

# ---- MAP.DRK ---------------------------------------------------------------
# ---- commit (only after every verification passed) -------------------------
[IO.File]::WriteAllBytes($drakm, $newDrakm)
if ($null -ne $newResi) { [IO.File]::WriteAllBytes($resi, $newResi) }
if ($sel.Contains('map')) {
    $mapBytes = [Convert]::FromBase64String($mapB64)
    if ((Get-Sha $mapBytes) -ne $mapSha) { Fail 'embedded MAP.DRK failed verification.' }
    [IO.File]::WriteAllBytes($map, $mapBytes)
}
if ($sel.Contains('hints')) {
    $questBytes = [Convert]::FromBase64String($questB64)
    if ((Get-Sha $questBytes) -ne $questSha) { Fail 'embedded QUEST.DRK failed verification.' }
    [IO.File]::WriteAllBytes((Join-Path $GamePath 'QUEST.DRK'), $questBytes)
}
# CONFIG.TAT: 0xFFFF at +0x0A means "ask for video card every launch"; 4 = always VGA.
# Only flip it if it is still the ask-me value - a player's own choice is left alone.
$cfg = Join-Path $GamePath 'CONFIG.TAT'
if ($sel.Contains('vga') -and (Test-Path $cfg)) {
    $cb = [IO.File]::ReadAllBytes($cfg)
    if ($cb.Length -gt 0x0B -and $cb[0x0A] -eq 0xFF -and $cb[0x0B] -eq 0xFF) {
        $cb[0x0A] = 4; $cb[0x0B] = 0; [IO.File]::WriteAllBytes($cfg, $cb)
        Write-Host '  CONFIG.TAT    - video-card menu skipped (always VGA)'
    }
}
Write-Host ''
Write-Host 'Patched successfully:' -ForegroundColor Green
Write-Host '  DRAKM.CC1     - compass, map (M), hints (H), shared XP, item names, bow, stat growth, ring effects'
Write-Host '  RESI_VGA.6C0  - readable spell font'
Write-Host '  MAP.DRK       - world map image (new file)'
Write-Host '  QUEST.DRK     - quest hints page for the H key (new file)'
Write-Host 'Originals are in _backup\original. Uninstall:  install.ps1 -Restore'
