#!/usr/bin/env python3
"""Drakkhen QOL patch - US GOG version. Python installer (stdlib only, no dependencies).

Same behavior as install.ps1: verifies your files are the stock US GOG release by SHA256,
backs them up, rebuilds the patched files FROM YOUR OWN GAME DATA, verifies the result
byte-for-byte against the reference build, and only then writes. Save files are never touched.

    python install.py            (run from the Drakkhen game folder, or pass the path)
    python install.py --restore  (uninstall: put the backed-up originals back)

Generated by make_patcher.py; do not edit by hand.
"""
import argparse, base64, hashlib, os, struct, sys

STOCK_DRAKM_SHA = '@@STOCK_DRAKM_SHA@@'
STEAM_DRAKM_SHA = '@@STEAM_DRAKM_SHA@@'   # GOG stock + Steam's own 1-byte protection skip
STEAM_FIX_OFF, STEAM_FIX_VAL = 0x11D87, 0x75   # revert that byte -> byte-identical to GOG stock
STOCK_RESI_SHA  = '@@STOCK_RESI_SHA@@'
MOD_DRAKM_SHA   = '@@MOD_DRAKM_SHA@@'
MOD_RESI_SHA    = '@@MOD_RESI_SHA@@'
MAP_SHA         = '@@MAP_SHA@@'

DIFF_DRAKM = '''@@DIFF_LINES@@'''
DIFF_RESI  = '''@@RDIFF_LINES@@'''
MAP_B64    = '@@MAP_B64@@'
QUEST_SHA  = '@@QUEST_SHA@@'
QUEST_B64  = '@@QUEST_B64@@'
FRAGS   = __import__('json').loads('''@@FRAGS_JSON@@''')
MODDEFS = __import__('json').loads('''@@MODDEFS_JSON@@''')
STOCK_COM_SHA = '@@STOCK_COM_SHA@@'
MENU4_DONE_SHA = '@@MENU4_DONE_SHA@@'
MENU4_RUNS = __import__('json').loads('''@@MENU4_RUNS@@''')


# ---- BPE codec (mirrors the reference drakpack.py) --------------------------
def bpe_decode(src, pos):
    out = bytearray()
    while True:
        n, more = src[pos], src[pos + 1]
        ln = src[pos + 2] | (src[pos + 3] << 8)
        pos += 4
        if n == 0:
            out += src[pos:pos + ln]; pos += ln
        else:
            code = src[pos:pos + n]; left = src[pos + n:pos + 2 * n]; right = src[pos + 2 * n:pos + 3 * n]
            pos += 3 * n
            t = [0] * 256; chain = [0] * (n + 1)
            for i in range(1, n + 1):
                chain[i] = t[code[i - 1]]; t[code[i - 1]] = i
            for b in src[pos:pos + ln]:
                stack = [(b, -1)]
                while stack:
                    b2, limit = stack.pop()
                    idx = t[b2]
                    if idx and 0 <= limit <= idx:
                        j = idx
                        while True:
                            j = chain[j]
                            if j == 0:
                                idx = 0; break
                            if j < limit:
                                idx = j; break
                    if idx == 0:
                        out.append(b2)
                    else:
                        stack.append((right[idx - 1], idx))
                        stack.append((left[idx - 1], idx))
            pos += ln
        if not more:
            return bytes(out), pos


def encode_raw(raw):
    out = bytearray()
    blocks = [raw[i:i + 0xFFC0] for i in range(0, len(raw), 0xFFC0)] or [b'']
    for i, b in enumerate(blocks):
        out += struct.pack('<BBH', 0, 1 if i < len(blocks) - 1 else 0, len(b)) + b
    return bytes(out)


def pack_container(chunks):
    bodies = [struct.pack('>II', len(encode_raw(c)), len(c)) + encode_raw(c) for c in chunks]
    offs, o = [], 0
    for b in bodies:
        offs.append(o); o += len(b)
    return (struct.pack('>H', len(chunks)) + b''.join(struct.pack('>I', x) for x in offs)
            + b''.join(bodies))


def unpack_container(data):
    n = struct.unpack_from('>H', data)[0]
    base = 2 + 4 * n
    res = []
    for i in range(n):
        o = struct.unpack_from('>I', data, 2 + 4 * i)[0]
        res.append(bpe_decode(data, base + o + 8)[0])
    return res


# ---- helpers ----------------------------------------------------------------
def sha(b): return hashlib.sha256(b).hexdigest()

def apply_diff(img, diff):
    img = bytearray(img)
    for line in diff.splitlines():
        line = line.strip()
        if not line:
            continue
        off, hexs = line.split(':')
        img[int(off):int(off) + len(hexs) // 2] = bytes.fromhex(hexs)
    return bytes(img)

def fail(msg):
    print('ERROR: ' + msg); sys.exit(1)


def apply_creator_fragments(chunk0, selected):
    """Chunk 0 of DRAKM.CC1 is the character creator - a second MZ image.  Mods that change
    what a new character starts with edit immediate operands there, so no relocation work is
    needed: lay the recorded byte runs back down in canonical order."""
    c = bytearray(chunk0)
    for name in FRAGS['order']:
        if name not in selected:
            continue
        for off, hx in FRAGS['frags'][name].get('writes0', []):
            b = bytes.fromhex(hx)
            c[off:off + len(b)] = b
    return bytes(c)


def apply_fragments(chunk1, selected):
    c = bytearray(chunk1)
    h = list(struct.unpack_from('<14H', c))
    ro, nrel, hdr = h[12], h[3], h[4] * 16
    for name in FRAGS['order']:
        if name not in selected:
            continue
        for off, hx in FRAGS['frags'][name]['writes']:
            b = bytes.fromhex(hx)
            c[off:off + len(b)] = b
    reps, drops, adds = {}, set(), []
    for name in FRAGS['order']:
        if name not in selected:
            continue
        f = FRAGS['frags'][name]
        for old, off, seg in f['rrep']:
            reps[old] = (off, seg)
        drops.update(f['rdrop'])
        adds += [(off, seg) for off, seg in f['radd']]
    entries = []
    for i in range(nrel):
        off, seg = struct.unpack_from('<HH', c, ro + 4 * i)
        lin = seg * 16 + off
        if lin in drops:
            continue
        if lin in reps:
            off, seg = reps[lin]
        entries.append((off, seg))
    entries += adds
    if ro + len(entries) * 4 > hdr:
        fail('relocation table overflow - report this selection as a bug')
    for k, (off, seg) in enumerate(entries):
        struct.pack_into('<HH', c, ro + 4 * k, off, seg)
    h[3] = len(entries)
    struct.pack_into('<14H', c, 0, *h)
    return bytes(c)


def ask_selection():
    print()
    print('Select mods to install (all are ON by default):')
    state = {k: True for k, _, _ in MODDEFS}
    while True:
        for n, (k, label, deps) in enumerate(MODDEFS, 1):
            print(' %2d. [%s] %s' % (n, 'X' if state[k] else ' ', label))
        ans = input('Toggle by number, A = all on, N = all off, ENTER = install checked: ').strip().lower()
        if ans == '':
            return {k for k, v in state.items() if v}
        if ans == 'a':
            state = {k: True for k in state}
        elif ans == 'n':
            state = {k: False for k in state}
        elif ans.isdigit() and 1 <= int(ans) <= len(MODDEFS):
            k = MODDEFS[int(ans) - 1][0]
            state[k] = not state[k]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('gamepath', nargs='?', default=os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument('--restore', action='store_true', help='undo the patch from the backup')
    ap.add_argument('--all', action='store_true', help='install every mod without asking')
    ap.add_argument('--mods', help='comma-separated mod keys to install (see --list)')
    ap.add_argument('--list', action='store_true', help='list selectable mods and exit')
    a = ap.parse_args()
    if a.list:
        for k, label, deps in MODDEFS:
            print('%-10s %s%s' % (k, label, (' (requires: %s)' % ','.join(deps)) if deps else ''))
        return
    g = a.gamepath
    drakm, resi = os.path.join(g, 'DRAKM.CC1'), os.path.join(g, 'RESI_VGA.6C0')
    mapf = os.path.join(g, 'MAP.DRK')
    bak = os.path.join(g, '_backup', 'original')
    if not os.path.exists(drakm) and os.path.exists(os.path.join(g, 'game', 'DRAKM.CC1')):
        g = os.path.join(g, 'game')          # Steam layout: files live in a game/ subfolder
        print("using Steam layout: game files in '%s'" % g)
        drakm, resi = os.path.join(g, 'DRAKM.CC1'), os.path.join(g, 'RESI_VGA.6C0')
        mapf = os.path.join(g, 'MAP.DRK')
        bak = os.path.join(g, '_backup', 'original')
    if not os.path.exists(drakm) or not os.path.exists(resi):
        fail("game files not found in '%s' - run from the Drakkhen folder or pass its path." % g)

    if a.restore:
        comb = os.path.join(bak, 'DRAKKHEN.COM')
        if os.path.exists(comb):
            open(os.path.join(g, 'DRAKKHEN.COM'), 'wb').write(open(comb, 'rb').read())
            print('restored DRAKKHEN.COM')
        for f in ('DRAKM.CC1', 'RESI_VGA.6C0'):
            src = os.path.join(bak, f)
            if not os.path.exists(src):
                fail('no backup at %s - nothing to restore.' % src)
            open(os.path.join(g, f), 'wb').write(open(src, 'rb').read())
            print('restored ' + f)
        if os.path.exists(mapf):
            os.remove(mapf); print('removed MAP.DRK (added by the patch)')
        qf = os.path.join(g, 'QUEST.DRK')
        if os.path.exists(qf):
            os.remove(qf); print('removed QUEST.DRK (added by the patch)')
        cfg = os.path.join(g, 'CONFIG.TAT')
        if os.path.exists(cfg):
            cb = bytearray(open(cfg, 'rb').read())
            if len(cb) > 0x0B:
                cb[0x0A:0x0C] = bytes([255, 255])
                open(cfg, 'wb').write(bytes(cb)); print('restored CONFIG.TAT video-card prompt')
        print('Game restored to stock. Save files were not touched.')
        return

    allkeys = [k for k, _, _ in MODDEFS]
    if a.mods:
        sel = set(x.strip() for x in a.mods.split(',') if x.strip())
        bad = sel - set(allkeys)
        if bad:
            fail('unknown mod keys: %s (use --list)' % ', '.join(sorted(bad)))
    elif a.all:
        sel = set(allkeys)
    else:
        sel = ask_selection()
    # dependency closure
    changed = True
    while changed:
        changed = False
        for k, _, deps in MODDEFS:
            if k in sel:
                for dep in deps:
                    if dep not in sel:
                        sel.add(dep); changed = True
                        print('note: %s requires %s - enabled automatically' % (k, dep))
    if not sel:
        print('nothing selected - nothing to do.'); return
    full = sel == set(allkeys)
    print('installing: ' + ', '.join(k for k in allkeys if k in sel))

    db, rb = open(drakm, 'rb').read(), open(resi, 'rb').read()
    if sha(db) == MOD_DRAKM_SHA and sha(rb) == MOD_RESI_SHA:
        print('Already patched with this version - nothing to do.'); return
    if sha(db) != STOCK_DRAKM_SHA and os.path.exists(os.path.join(bak, 'DRAKM.CC1')):
        db = open(os.path.join(bak, 'DRAKM.CC1'), 'rb').read()
        print('DRAKM.CC1 is modified; using the backup copy as the stock source.')
    if sha(rb) != STOCK_RESI_SHA and os.path.exists(os.path.join(bak, 'RESI_VGA.6C0')):
        rb = open(os.path.join(bak, 'RESI_VGA.6C0'), 'rb').read()
        print('RESI_VGA.6C0 is modified; using the backup copy as the stock source.')
    steam = sha(db) == STEAM_DRAKM_SHA
    if steam:
        print("Steam release detected (DRAKM.CC1 carries the Steam 1-byte protection skip).")
    if not steam and sha(db) != STOCK_DRAKM_SHA:
        fail("DRAKM.CC1 is not a known US release.\n"
             "  yours:       %s (%d bytes)\n"
             "  known GOG:   %s\n"
             "  known Steam: %s\n"
             "If this is an unmodified US GOG or Steam install, please report these lines at\n"
             "https://github.com/Innsomatico/DrakkhenPC-QOL/issues - the hash is what we need.\n"
             "Nothing was changed." % (sha(db), len(db), STOCK_DRAKM_SHA, STEAM_DRAKM_SHA))
    if sha(rb) != STOCK_RESI_SHA:
        fail("RESI_VGA.6C0 is not the stock US version.\n"
             "  yours: %s (%d bytes)\n"
             "  known: %s\n"
             "Please report these lines at https://github.com/Innsomatico/DrakkhenPC-QOL/issues.\n"
             "Nothing was changed." % (sha(rb), len(rb), STOCK_RESI_SHA))

    os.makedirs(bak, exist_ok=True)
    for name, data in (('DRAKM.CC1', db), ('RESI_VGA.6C0', rb)):
        p = os.path.join(bak, name)
        if not os.path.exists(p):
            open(p, 'wb').write(data); print('backed up ' + name)

    print('decoding DRAKM.CC1 ...')
    chunks = unpack_container(db)
    if steam:
        c1 = bytearray(chunks[1])
        c1[STEAM_FIX_OFF] = STEAM_FIX_VAL    # normalize Steam's byte back to stock
        chunks[1] = bytes(c1)
    engine_sel = set(FRAGS['order']) & sel
    chunks[0] = apply_creator_fragments(chunks[0], engine_sel)
    chunks[1] = apply_fragments(chunks[1], engine_sel)
    new_drakm = pack_container(chunks)
    if full and sha(new_drakm) != MOD_DRAKM_SHA:
        fail('rebuilt DRAKM.CC1 failed verification - nothing was changed.')
    if not full:
        print('note: partial selection - engine verified structurally (full-set hash check skipped).')

    new_resi = None
    if 'spellfont' in sel:
        print('decoding RESI_VGA.6C0 ...')
        rdec = apply_diff(bpe_decode(rb, 8)[0], DIFF_RESI)
        body = encode_raw(rdec)
        new_resi = struct.pack('>II', len(body), len(rdec)) + body
        if sha(new_resi) != MOD_RESI_SHA:
            fail('rebuilt RESI_VGA.6C0 failed verification - nothing was changed.')

    open(drakm, 'wb').write(new_drakm)
    if new_resi is not None:
        open(resi, 'wb').write(new_resi)
    if 'map' in sel:
        map_bytes = base64.b64decode(MAP_B64)
        if sha(map_bytes) != MAP_SHA:
            fail('embedded MAP.DRK failed verification.')
        open(mapf, 'wb').write(map_bytes)
    if 'hints' in sel:
        quest_bytes = base64.b64decode(QUEST_B64)
        if sha(quest_bytes) != QUEST_SHA:
            fail('embedded QUEST.DRK failed verification.')
        open(os.path.join(g, 'QUEST.DRK'), 'wb').write(quest_bytes)
    # DRAKKHEN.COM: remove the main menu's video-card entry (text lines + jump table).
    if 'menu4' in sel:
        comp = os.path.join(g, 'DRAKKHEN.COM')
        cd = bytearray(open(comp, 'rb').read())
        if sha(bytes(cd)) == MENU4_DONE_SHA:
            print('  DRAKKHEN.COM  - already patched')
        elif sha(bytes(cd)) != STOCK_COM_SHA:
            fail('DRAKKHEN.COM is not the stock US build - not touching it.')
        else:
            cb = os.path.join(bak, 'DRAKKHEN.COM')
            if not os.path.exists(cb):
                open(cb, 'wb').write(bytes(cd)); print('backed up DRAKKHEN.COM')
            for off, hx in MENU4_RUNS:
                b = bytes.fromhex(hx)
                cd[off - 0x100:off - 0x100 + len(b)] = b
            if sha(bytes(cd)) != MENU4_DONE_SHA:
                fail('patched DRAKKHEN.COM failed verification - nothing was changed.')
            open(comp, 'wb').write(bytes(cd))
            print('  DRAKKHEN.COM  - video-card menu entry removed (4-item main menu)')

    # CONFIG.TAT: 0xFFFF at +0x0A = "ask for video card"; 4 = always VGA. Only flip the ask-me value.
    cfg = os.path.join(g, 'CONFIG.TAT')
    if 'vga' in sel and os.path.exists(cfg):
        cb = bytearray(open(cfg, 'rb').read())
        if len(cb) > 0x0B and cb[0x0A] == 0xFF and cb[0x0B] == 0xFF:
            cb[0x0A:0x0C] = bytes([4, 0])
            open(cfg, 'wb').write(bytes(cb))
            print('  CONFIG.TAT    - video-card menu skipped (always VGA)')
    print('')
    print('Patched successfully:')
    print('  DRAKM.CC1     - compass, M-key world map, shared XP, item names, bow buff')
    print('  RESI_VGA.6C0  - readable spell font')
    print('  MAP.DRK       - world map image (new file)')
    print('  QUEST.DRK     - quest hints page for the H key (new file)')
    print('Originals are in _backup/original. Uninstall:  python install.py --restore')


if __name__ == '__main__':
    main()
